language: node
node_js:
  - 12

cache:
  directories:
    - node_modules # NPM packages
env:
  global:
    #Aws account
    - secure: VR0UJ3r9BbINQAbMMMdWfJ14RbDE4qMZdsxxqA7mlF2jXAHsnuzbd8RlXPUiXjBkoKEEmP/rpOCVMXP7LYXr8YV5VmAeEHn1B0LmdiG7OdvSG5xBGcAUahaOyJ6h302GQyQB+NzUqHkVrD+064ZdX8PRWT9pNBJQOr5cd6LVEtqU6RqQXplQa8OeyLtW36Nw4/Uk9wMm3x12IDNe5aaxjpDNf1sIo/I3kQ/drleLT0Ma3hXDKA8kMiXNkTLEkrcR9GWI+T9doqb7b7m3MMn+m7Zl19KAI2JzyMq/BtPECN+ChWAsPQvg1fplJTlH1wNMg4bNTUp025G4YJYK708SBlSN+SFOcPCXh4Wr8Dw6GbMzitOSGTlqH0ShUQxvU71rgz6TYE6WXu3uVFV/qcjMAtr9QE8YumN2G2b3ENezwLu9MI1CSSO3DI/agObXzUubGJkHM56i9+0QmVgkJtI1ToC2Lk0fJzQWpaMgqVFG1y0WHiE6Qgxw8hYaEfSLjzaSirYq0aZ4K93r+Sr/IBuCcQTqCfJayjGCKrQfBOn3TSrk/N/EfX2RN5iRNe9kN0tF0w53UTPR9SIScVsK88Pon2NC+YjXHGR3QpYRObgp+WB0BaQuqbE1kOHao7NlqODHcQeVDz3TqwxadXTON2Vuv8Yo1vJzNelU7M4Q2FbuXKw=
    - secure: g73+o8+skxgZCGqJOaRobLR7+1yzz4L8f5qUGKhMpCGy+7IUWfWfYpzqE6yTAti99Q69cpxw6srQNdDOSfDDuLLORmOLzDHl4RomnaC/12IHkCmXSBMWS7nrSDHVLGVNw8gAXbkc5AQx6Exr6gb91Br8W85OhHloUgmS1UatU93Hvkai9fn4nTftAvNbbrriZwABlItMjpQBXcVQUAAnz/SMIOcZ/kwMVWuSLt6wdJv8yijXDMuUEe0GOqLGB49Gq+BsWAIkn495uOpIThrBxClvU5LzHEwppw2CB74jWxeD6J/Og11m/DRBK/Lp0XuAj0Bvxwre54ZZCTNFIpe4Rfx5CmiUi6QGtvrXJy0PrlCQ85ti6IQc0QPDxnq+bvZp/N0JufBpioJhH41G4FDbYLKVRcPL0cLW3Y8F5LMy6Nikt4AwczYvOOPVSLQb6deeaAWpLRZXPyOKg6wX17f+xK0N6TBrqrGkFnZN4upD9V90BlTwOI1cSKeDtc+e7wsAX3dqppC/0fuhyBMWmgnJ/ziIYi1TuOvSaIb1DC/XWFMVhS41ag7RRIkHpoYoGpuYMTseQoGzHpFN+pJaLln9GF5fZ1zfKpu0HZphwsjol5lBrYK11LO6prU4oqWCf47AXGStvwVlXqRRzkUFr6EBG0gaBI/S+HPBcEVrtMo74cE=




before_deploy:
  #Deploy the javascript file to s3 bucket
  - zip myzip.zip main.js
  - mkdir build
  - mv myzip.zip build
  - ls

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: "aws-lambda-bucket-leifhaa"
  upload_dir: "v1.0.0"
  skip_cleanup: true
  local_dir: build

branches:
  only:
    - master