language: javascript

env:
  global:
    #Aws account
    - secure: Imma6OqmLDGYYDDoCAnq2+F/1HQMPl9LvOHjB4VUl/j8ce9iUUW2zmacgoo5YrZXl88WewtyTbYhPAcEWO9bboghRvGP6+CC0Ov0YJDvPoLTEB+pzmR+GWwI8+xzRUPFCYkgH6zcXoKkvVI2HZlFDQ7Obln0UG/UUkRige4k8VMOLND2skSRJYgSPCQVjWZlD9D2PyYABBItKTMw/hV+DG6oVUyBPb/lqyyygqNzHrqerAC/J5XmNne6gWWyMK8+PnctInpBvC5lX9XA6tY/LUgIWMkpknXkvKyX/g7Xn9R6poPV5kK1ZNGnnwD3FhhlSrpxIoKgGiCfkOU4Tqxo7IqdGmA0fWh10Z4MRuvx1uMfuvsPkKs9kHSjh12ISGD8G7McTofc0r+YE7ZK3zoMWjyc83NXdVvZN2JQEO2MAyBgZ87iyMj5lcaWbWkqJ6I0pXNMfcooHkKmlsYl4FuAMugRN7lEXC0qL5E/9ILz2Nj2RTscKG90dBMlyAAddJc+PHv1iyG8V+ltvVQgvSli3W9B/d9OUwTveC5beP6wa9lXWJ43M5lv4D4OuSPynz45gA8OvvLGb7whMHYSVVmFi0RTcHHm5IqaudG5vj0chHXLYzyBzzHPgRjSs3nH8REt4AGZpxM3VtiLcbmpkpSke/SAw2HuJa27DiyHxMqcmug=
    - secure: oaTduh5vhV2WozIFBdNWmuEp5PkCq7VJAjMRtCnJqnODIbCpLWoi8rbLKldZcrySk8pg9uFAMUJe682dRbnJl1qX+mH58///AOvkVXpbmM818dhV0VqPCX/0WSkDNIik99KFyInHtMZEfCHIICsSUSS7th3ig3/QGXgX7U1GfuC2shkVnWvjI1i6W/4jWsm+jV2i9dvISAG+aYgincrwx+M1kEr8rE5rL2ICpNPqaUUBNju8MlCAxQt0/44fundtRqqyOLNd2GNayriCS6uwZNRSv7YN3qW46eiu0RC9St1+gEhgMSJz4GjZVUzXmvVQzZ5kuPRhfF+1NKFDgQt1RJLvSBcpV75HxkqxA+0phorozC4XuOGM6ODC3OUEZLnqygDyp1Qplk0fxn7gqiCw2CUJxK+rdP3Z5SUxRkaJbEDWFUyqqTUmxIBLHbHW/5j4LtMlkI9TzSmjRP5YfNWWXWnikBysHotAQmMFR7PINJmtkSrXxoDv9Djiu/sjO2hddYHSdpIZ3bFRFpJTTrpt6YM+FlxZo8Ju3wiJjTOpxxPR6w3xTRV1mC3qvksajI4XIN9RyTqN/hzETmtVR+XUulAcw8ergmG/oOd3nzK8Ivwd56UpgnFwgUaFEFpvABgNftOVU1eSAqmdBW/509DT69slqTu0WZU8g4mxUsUhdV4=

#Skip tests
script: 'true'

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: "aws-lambda-bucket-leifhaa"